import { createStitches } from "@stitches/react";

export const { styled, css, getCssText } = createStitches({
  theme: {
    colors: {
      primary: "$purple900",
      secondary: "$orange900",
      black: "#000000",
      white: "#FFFFFF",
      gray100: "#F7F8F9",
      gray200: "#F4F6F7",
      gray300: "#EDEFF0",
      gray400: "#DBE0E1",
      gray500: "#CCD1D4",
      gray600: "#B9BEC1",
      gray700: "#9FA6A9",
      gray800: "#65696B",
      gray900: "#333333",
      orange100: "#FEE1D7",
      orange200: "#FDD1C3",
      orange300: "#FDC2AF",
      orange400: "#FCB39B",
      orange500: "#FBA487",
      orange600: "#FB9573",
      orange700: "#FA855F",
      orange800: "#FA764B",
      orange900: "#F96737",
      purple100: "#F2E4FF",
      purple200: "#EBD5FF",
      purple300: "#DBB5FF",
      purple400: "#CC96FF",
      purple500: "#BD76FF",
      purple600: "#8D4CC4",
      purple700: "#672091",
      purple800: "#630E88",
      purple900: "#5F0080",
    },
    space: {
      1: "2px",
      2: "4px",
      3: "8px",
      4: "12px",
      5: "16px",
      6: "24x",
      7: "32px",
      8: "40px",
      9: "48px",
      10: "64px",
      11: "80px",
      12: "96px",
      13: "160px",
    },
    fontSizes: {
      1: "12px",
      2: "13px",
      3: "14px",
      4: "15px",
      5: "16px",
      6: "18px",
      7: "20px",
      8: "24px",
    },
    radii: {
      1: "4px",
      2: "6px",
      3: "8px",
      4: "12px",
    },
  },
  utils: {
    p: (value: string) => ({ padding: value }),
    pt: (value: string) => ({ paddingTop: value }),
    pr: (value: string) => ({ paddingRight: value }),
    pb: (value: string) => ({ paddingBottom: value }),
    pl: (value: string) => ({ paddingLeft: value }),
    px: (value: string) => ({ paddingLeft: value, paddingRight: value }),
    py: (value: string) => ({ paddingTop: value, paddingBottom: value }),
    m: (value: string) => ({ margin: value }),
    mt: (value: string) => ({ marginTop: value }),
    mr: (value: string) => ({ marginRight: value }),
    mb: (value: string) => ({ marginBottom: value }),
    ml: (value: string) => ({ marginLeft: value }),
    mx: (value: string) => ({ marginLeft: value, marginRight: value }),
    my: (value: string) => ({ marginTop: value, marginBottom: value }),
  },
});

export const Flex = styled("div", {
  display: "flex",
  variants: {
    row: { true: { flexDirection: "row" } },
    col: { true: { flexDirection: "column" } },
    justify: {
      start: { justifyContent: "start" },
      end: { justifyContent: "end" },
      center: { justifyContent: "center" },
      between: { justifyContent: "space-between" },
      around: { justifyContent: "space-around" },
      evenly: { justifyContent: "space-evenly" },
    },
    justifyItems: {
      start: { justifyItems: "start" },
      end: { justifyItems: "end" },
      center: { justifyItems: "center" },
      stretch: { justifyItems: "stretch" },
    },
    align: {
      start: { alignItems: "start" },
      end: { alignItems: "end" },
      center: { alignItems: "center" },
      baseline: { alignItems: "baseline" },
      stretch: { alignItems: "stretch" },
    },
  },
});

export const Relative = styled("div", {
  position: "relative",
});

export const Absolute = styled("div", {
  position: "absolute",
});
